version: '3'

services:
  geoserver:
    image: cartoview/geoserver_docker:tomcat
    restart: unless-stopped
    hostname: geoserver
    build:
      context: ./
      dockerfile: docker/GeoserverDockerfile
    user: root
    ports:
      - "8080:8080"